language: ruby
rvm:
- 2.6.1
deploy:
  provider: heroku
  api_key:
    secure: tdmX9bYkQOoJYjBhTEHjQ06tdkF649WLNxBKO7oZq9s3/TtQxQcz5kDUgasCqf/3AOsgKuBBl38XKfAHo9SfTrB+2r/Kmlogyc7z60Crrub0lyS/NX11V3IbTarlGcumCHS0dvc1HqZDwyL5VfnmFRngLNJAtOoGk9TFuIdS2RJMUiBGbzIjcRta7FIX2dfeoeeQxgq4BrqoZi8XBckncWusJtbmUHGiQy10tvZ1CBejU7GRwJ22XH+XTbOBLuAm7Jr41WOytkcnK0eWDuV9Qr0/UP7/pcwwcAuLTKN0Qv5H7RoM1TepgaaVMKP4tGKBOMcqY4DVnQsuOnOysgUnzkgf+Ui1ix+bsi8ZmGfrQ8xuzMRxIrCJVVLLZ/UKznpaQYVHMDZ5/7WfEjFsYqCryP1zr4bYkW4jShghQyT6jscVbl+QBFBMqpErJ6c1bXquiH30VIK3kZ+3vWoHeOI/VvGcWR9AKygDJdi3ASKoTstrfxUrFwKwlpnnIT5pbtjLDs90QurBf9MqAYj9tiyxYtL36b+Tlj5oIWqGALxsGothw7yDjGsdkx0dNCA9QjwCYbYL2ikzVl90ihVN1/nPS2Ci6M0C6jxqDN7CfHXvAqsZZkf9P+oMThETZCEfqmyvGY53qQqxw/zinANwKV1q2B49zH/cb+U/gPKtX4c54tU=
  app: Test
  on:
    repo: Oxyh/Test
